# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-14 00:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20160313_1945'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='owner',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.Restaurant'),
            preserve_default=False,
        ),
    ]
