# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-13 17:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20160313_0154'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='allergies',
        ),
        migrations.AddField(
            model_name='order',
            name='allergies',
            field=models.CharField(default='Eggs', max_length=512),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='notes',
            field=models.CharField(default='No Pickles', max_length=512),
            preserve_default=False,
        ),
    ]
