# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-14 02:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20160313_2150'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='owner',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='owned_restaurant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Restaurant'),
        ),
    ]
