# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-13 17:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20160313_1728'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='allergies',
            field=models.CharField(default='Allergies', max_length=512),
            preserve_default=False,
        ),
    ]
