# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-13 20:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_userprofile_allergies'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='allergies',
        ),
        migrations.AlterField(
            model_name='order',
            name='notes',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='allergies',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
