# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-14 02:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20160313_2206'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='owned_restaurant',
            new_name='owner',
        ),
    ]
