# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-13 21:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_userprofile_owner'),
        ('main', '0008_auto_20160313_2023'),
    ]

    operations = [
    ]
